<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VIN_f.6' shared service.

return $this->privates['.service_locator.VIN_f.6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire' => '?',
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire' => '?',
]);
