<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2R_wH2s' shared service.

return $this->privates['.service_locator.2R_wH2s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteDepotController::inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteDepotController::register' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire_Utilisateur' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\CompteDepotController:inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteDepotController:register' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire_Utilisateur' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\CompteDepotController::inserer' => '?',
    'App\\Controller\\CompteDepotController::register' => '?',
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire_Utilisateur' => '?',
    'App\\Controller\\CompteDepotController:inserer' => '?',
    'App\\Controller\\CompteDepotController:register' => '?',
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire_Utilisateur' => '?',
]);
