<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VZ8eYfB' shared service.

return $this->privates['.service_locator.VZ8eYfB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteDepotController::inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteDepotController::register' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire_Utilisateur' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\UtilisateurController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UtilisateurController::update_Compte' => ['privates', '.service_locator.QKEbH36', 'get_ServiceLocator_QKEbH36Service.php', true],
    'App\\Controller\\UtilisateurController::update_Status' => ['privates', '.service_locator.QKEbH36', 'get_ServiceLocator_QKEbH36Service.php', true],
    'App\\Controller\\CompteDepotController:inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteDepotController:register' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire_Utilisateur' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\UtilisateurController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UtilisateurController:update_Compte' => ['privates', '.service_locator.QKEbH36', 'get_ServiceLocator_QKEbH36Service.php', true],
    'App\\Controller\\UtilisateurController:update_Status' => ['privates', '.service_locator.QKEbH36', 'get_ServiceLocator_QKEbH36Service.php', true],
], [
    'App\\Controller\\CompteDepotController::inserer' => '?',
    'App\\Controller\\CompteDepotController::register' => '?',
    'App\\Controller\\UtilisateurController::Ajouter_Partenaire_Utilisateur' => '?',
    'App\\Controller\\UtilisateurController::login' => '?',
    'App\\Controller\\UtilisateurController::update_Compte' => '?',
    'App\\Controller\\UtilisateurController::update_Status' => '?',
    'App\\Controller\\CompteDepotController:inserer' => '?',
    'App\\Controller\\CompteDepotController:register' => '?',
    'App\\Controller\\UtilisateurController:Ajouter_Partenaire_Utilisateur' => '?',
    'App\\Controller\\UtilisateurController:login' => '?',
    'App\\Controller\\UtilisateurController:update_Compte' => '?',
    'App\\Controller\\UtilisateurController:update_Status' => '?',
]);
