<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1CTvAOK\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1CTvAOK/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container1CTvAOK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container1CTvAOK\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container1CTvAOK\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '1CTvAOK',
    'container.build_id' => 'f8fad473',
    'container.build_time' => 1565018830,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1CTvAOK');
