<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5SbXxa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5SbXxa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5SbXxa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5SbXxa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW5SbXxa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W5SbXxa',
    'container.build_id' => '819862f6',
    'container.build_time' => 1564665583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5SbXxa');
