<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ87ZFGn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ87ZFGn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ87ZFGn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ87ZFGn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ87ZFGn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z87ZFGn',
    'container.build_id' => '63190ef7',
    'container.build_time' => 1565006661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ87ZFGn');
